version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fagame-db
    environment:
      POSTGRES_USER: fagame
      POSTGRES_PASSWORD: fagame123
      POSTGRES_DB: fagame
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fagame"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fagame-app
    environment:
      DATABASE_URL: "postgresql://fagame:fagame123@postgres:5432/fagame?schema=public"
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  postgres_data: